version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"

  ollama:
    image: ollama/ollama:0.3.1
    container_name: ollama
    volumes:
      - /home/mathanraj-sharma/Desktop/learnings/codes/llm-zoomcamp-homework/ollama_files:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
          reservations:
            devices:
              - driver: nvidia
                count: all
                capabilities: [gpu]
